name: Gerar notícia automática

on:
  schedule:
    - cron: '*/3 * * * *' # Executa a cada 3 minutos
  workflow_dispatch: # Permite execução manual

  git commit -am "Corrigindo workflow desaparecido"
git push
  
name: Gerar notícia automática

on:
  workflow_dispatch:

jobs:
  gerar-noticia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Gerar notícia
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: node gerador_noticias.js

      - name: Commit e push do noticias.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/noticias.json
          git commit -m "Notícia gerada automaticamente" || echo "Nada para commitar"
          git push
